-- 013_preseason_prev_year_record_2026.sql
-- 2025 overall win-loss record -> team_preseason_stats.prev_year_record.
-- Source: 2025 final standings, "Overall W-L" column (includes bowl/playoff games,
-- which is why Indiana shows 16-0 and Alabama 11-4).
--
-- 136 rows, not 138. North Dakota State and Sacramento State played 2025 in FCS
-- and do not appear in the FBS standings, so their prev_year_record stays NULL.
--
-- UPDATE, not upsert -- the 2026 rows already exist.
-- Every team_id was verified against teams.id.

UPDATE team_preseason_stats AS p
SET prev_year_record = v.record
FROM (VALUES
  ('indiana', '16-0'),
  ('miami', '13-3'),
  ('ole-miss', '13-2'),
  ('oregon', '13-2'),
  ('byu', '12-2'),
  ('georgia', '12-2'),
  ('james-madison', '12-2'),
  ('north-texas', '12-2'),
  ('ohio-state', '12-2'),
  ('texas-tech', '12-2'),
  ('alabama', '11-4'),
  ('navy', '11-2'),
  ('texas-a-m', '11-2'),
  ('tulane', '11-3'),
  ('utah', '11-2'),
  ('virginia', '11-3'),
  ('houston', '10-3'),
  ('kennesaw-state', '10-4'),
  ('notre-dame', '10-2'),
  ('oklahoma', '10-3'),
  ('old-dominion', '10-3'),
  ('texas', '10-3'),
  ('unlv', '10-4'),
  ('vanderbilt', '10-3'),
  ('western-michigan', '10-4'),
  ('arizona', '9-4'),
  ('boise-state', '9-5'),
  ('duke', '9-5'),
  ('east-carolina', '9-4'),
  ('fresno-state', '9-4'),
  ('georgia-tech', '9-4'),
  ('hawaii', '9-4'),
  ('illinois', '9-4'),
  ('iowa', '9-4'),
  ('jacksonville-state', '9-5'),
  ('louisville', '9-4'),
  ('michigan', '9-4'),
  ('new-mexico', '9-4'),
  ('ohio', '9-4'),
  ('smu', '9-4'),
  ('san-diego-state', '9-4'),
  ('south-florida', '9-4'),
  ('tcu', '9-4'),
  ('uconn', '9-4'),
  ('usc', '9-4'),
  ('wake-forest', '9-4'),
  ('washington', '9-4'),
  ('western-kentucky', '9-4'),
  ('arizona-state', '8-5'),
  ('iowa-state', '8-4'),
  ('louisiana-tech', '8-5'),
  ('memphis', '8-5'),
  ('minnesota', '8-5'),
  ('missouri', '8-5'),
  ('nc-state', '8-5'),
  ('pittsburgh', '8-5'),
  ('tennessee', '8-5'),
  ('toledo', '8-5'),
  ('troy', '8-6'),
  ('arkansas-state', '7-6'),
  ('army', '7-6'),
  ('california', '7-6'),
  ('central-michigan', '7-6'),
  ('cincinnati', '7-6'),
  ('clemson', '7-6'),
  ('delaware', '7-6'),
  ('florida-international', '7-6'),
  ('georgia-southern', '7-6'),
  ('lsu', '7-6'),
  ('miami-oh', '7-7'),
  ('missouri-state', '7-6'),
  ('nebraska', '7-6'),
  ('northwestern', '7-6'),
  ('penn-state', '7-6'),
  ('southern-miss', '7-6'),
  ('texas-state', '7-6'),
  ('utsa', '7-6'),
  ('washington-state', '7-6'),
  ('coastal-carolina', '6-7'),
  ('kansas-state', '6-6'),
  ('louisiana', '6-7'),
  ('utah-state', '6-7'),
  ('akron', '5-7'),
  ('app-state', '5-8'),
  ('auburn', '5-7'),
  ('baylor', '5-7'),
  ('buffalo', '5-7'),
  ('florida-state', '5-7'),
  ('kansas', '5-7'),
  ('kent-state', '5-7'),
  ('kentucky', '5-7'),
  ('marshall', '5-7'),
  ('mississippi-state', '5-8'),
  ('rice', '5-8'),
  ('rutgers', '5-7'),
  ('temple', '5-7'),
  ('ucf', '5-7'),
  ('air-force', '4-8'),
  ('ball-state', '4-8'),
  ('bowling-green', '4-8'),
  ('eastern-michigan', '4-8'),
  ('florida', '4-8'),
  ('florida-atlantic', '4-8'),
  ('liberty', '4-8'),
  ('maryland', '4-8'),
  ('michigan-state', '4-8'),
  ('new-mexico-state', '4-8'),
  ('north-carolina', '4-8'),
  ('south-alabama', '4-8'),
  ('south-carolina', '4-8'),
  ('stanford', '4-8'),
  ('tulsa', '4-8'),
  ('uab', '4-8'),
  ('west-virginia', '4-8'),
  ('wisconsin', '4-8'),
  ('wyoming', '4-8'),
  ('colorado', '3-9'),
  ('middle-tennessee', '3-9'),
  ('nevada', '3-9'),
  ('northern-illinois', '3-9'),
  ('san-jos-state', '3-9'),  -- San Jose State
  ('syracuse', '3-9'),
  ('ucla', '3-9'),
  ('ul-monroe', '3-9'),
  ('virginia-tech', '3-9'),
  ('arkansas', '2-10'),
  ('boston-college', '2-10'),
  ('colorado-state', '2-10'),
  ('oregon-state', '2-10'),
  ('purdue', '2-10'),
  ('sam-houston', '2-10'),
  ('utep', '2-10'),
  ('charlotte', '1-11'),
  ('georgia-state', '1-11'),
  ('oklahoma-state', '1-11'),
  ('massachusetts', '0-12')
) AS v(team_id, record)
WHERE p.team_id = v.team_id
  AND p.season_year = 2026;

-- Verification:
--   SELECT count(*) FROM team_preseason_stats
--   WHERE season_year = 2026 AND prev_year_record IS NOT NULL;   -- expect 136
